### ISSUE TITLE
Container update strategies - how to update containers when there is a new image on the registry?

### ISSUE THREAD

**Issue by adrinux** [containers/ansible-podman-collections#266]
Kind: Support Request

I'm migrating several self-hosted applications from docker to podman. These are generally 'official' containers that projects use to distribute their applications via the docker.io registry. (So not containers that I want to modify internally.)

My previous strategy was to have Ansible compile a docker-compose.yml which I then ran through docker-compose on the server. This has an easy manual way to update the containers ```docker-compose pull && docker-compose up -d```.

I've successfully got one Podman pod up and running using this ansible-podman-collection (currently working on a systemd service to keep it up and running), but I'm troubled by how I can update the containers within the pod.

- There is some documentation on podman auto-update which doesn't look useful in the context of 'official' docker containers. 
- There is the possibility to ```podman generate systemd --new``` and have podman rebuild the containers itself - but that essentially takes the creation or removal of containers/pods away from Ansible, which feels wrong (also looks like they would get recreated on every reboot, which sounds bad for startup times).

So I'm wondering what strategies you use or imagine using to update your container/pods built with ansible.podman.
A container update play that removes and recreates containers? Optionally checking if the registry has a new version available?

**Comment by phongngthanh** [comment]
Currently it's possible to auto update the container running on systemd via setting a label in the container, which is already possible in the podman-ansible module. The missing piece is to create a podman-ansible systemd module, which can create and run systemd file for selected container (or pod), it's not available yet however (see issue #18 for more info), and making the module might not be trivial when you include the systemd file for pod. I would like to work on this eventually since it's the only missing part to make a podman system fully functional using ansible for selfhoster, but I haven't got the time yet.
For a current patch work that I use, I force pull container images using ansible-podman image module to update the image, then restart the computer. At startup, I rerun my container creation playbook, which will run the container with the updated image. It doesn't recreate unchanged container, so startup time is acceptable at least.

**Comment by adrinux** [comment]
Thanks. I clearly have a bit more thinking to do around this.
