### ISSUE TITLE
Shouldn't containers.podman.podman_login be idempotent?

### ISSUE THREAD

**Issue by nodje** [containers/ansible-podman-collections#426]
Using the default molecule scenario which include an idempotency test, which checks that every task of a role returns change=false on a second run, I noticed that containers.podman.podman_login was returning change=true, even the auth.json file was already existing with the same credentials.

There might be reasons why the actual behavior is expected, but as far as I'm concerned with my usage it'd seem normal to receive a change=false when running containers.podman.podman_login with credentials already stored in auth.json.

**Comment by sshnaidm** [comment]
If it's only question of comparing old and new `auth.json`, I think it should be possible to do.

**Comment by nodje** [comment]
To me the question really is: is the module podman_login idempotent ? (I assume all modules strive to be idempotent)
If not, what makes it idempotent? --> probably: if a login already occurred with a credential, it shouldn't try to login again and should return change status to false

**Comment by sshnaidm** [comment]
As far as I can say it's not idempotent now. I agree we could improve and add idempotency. The question is: is same `auth.json` good enough to say we're logged in?
Or probably we can use same mechanism as in `podman_login_info` module, like here: https://github.com/containers/ansible-podman-collections/blob/20a982b564e725758505df917e437b83505e0fe2/plugins/modules/podman_login_info.py#L68

@clelange @jthiatt any thoughts?

**Comment by clelange** [comment]
In the [`podman login` docs](https://docs.podman.io/en/latest/markdown/podman-login.1.html) it says that the username+password combination is simply stored as base64 in the `auth.json` file, so having this file unchanged would imply that nothing has changed. Regarding the use of `podman_login_info`: The `podman login --get-login` command seems to only return the username, but doesn't actually check if the login still works (haven't tested this though). I would therefore think that the login command should still try to actually log in, and we should check the JSON file before and after for changes. Otherwise, we'd have to add a "force" option for the login command to force overwriting an existing (but possibly outdated) login.
