### ISSUE TITLE
Create podman login module

### ISSUE THREAD

**Issue by sshnaidm** [containers/ansible-podman-collections#93]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Create podman module that logs in to container registries.

**Comment by cfelder** [comment]
containers.podman.podman_image supports username and password.

isn't this sufficient?

**Comment by sshnaidm** [comment]
Probably for most of cases, but I'd like to have it separate as well for one time login for the whole session.

**Comment by istolpov** [comment]
@sshnaidm hi, Sergey.

No, that is not enough, since there is an ongoing community process of migration to podman.

Consider this:

1) Company has a role that performs initial setup (including docker login)
2) Company also has hundreds of roles for different containers, image pushes, whatever else.

Now, with your approach that's potentially hundreds upon hundreds lines of code in hundreds of files to add credentials to which is a) cumbersome, b) clutter.

With a login module that's 5 LOC of change in one file.

**Comment by sshnaidm** [comment]
@istolpov I'm only for creating such module :smile:

**Comment by sshnaidm** [comment]
Docs: https://containers.github.io/ansible-podman-collections/podman_login_module.html#ansible-collections-containers-podman-podman-login-module
